15 missing implementation of ner module
alexandrainst/AIAI-eval pull request #54
Opened 2022-09-02 12:40 UTC by AJDERS

This PR introduces:

* Functionality for NER.
* Tests for NER.
* Modifications to `test_task.py` such that certain tests are skipped based on the input task fixture.
* Minor changes to sequence classification tests.

2022-09-02 16:01 UTC, saattrupdan requested changes

2022-09-02 16:01 UTC, saattrupdan commented on tests/test_named_entity_recognition.py
> +        )
```suggestion
        assert set(tokenised_dataset.features.keys()) == {
            "text",
            "labels",
            "input_ids",
            "token_type_ids",
            "attention_mask",
            "tokens",
            "lemmas",
            "sent_id",
            "tok_ids",
            "pos_tags",
            "morph_tags",
            "dep_ids",
            "dep_labels",
            "ner_tags",
        }
```

2022-09-02 16:01 UTC, saattrupdan commented on tests/test_task.py
> +            pytest.skip("skipped on this task: {}".format(task.task_config.name))
```suggestion
            pytest.skip(f"Skipped for the {task.task_config.name} task.")
```

2022-09-05 07:31 UTC, AJDERS commented on src/aiai_eval/named_entity_recognition.py
> +            )
Ill open a seperate issue :)

2022-09-05 07:52 UTC, saattrupdan approved these changes
LGTM!

2022-09-05 07:53 UTC, merged