39 offensive text detection evaluation
alexandrainst/AIAI-eval pull request #61
Opened 2022-09-06 14:03 UTC by AJDERS

This PR introduces a new task `offensive`, for offensive text classification.

2022-09-06 14:17 UTC, saattrupdan requested changes

2022-09-06 14:17 UTC, saattrupdan commented on src/aiai_eval/task_configs.py
> +        ),
```suggestion
        Label(
            name="NOT_OFFENSIVE",
            synonyms=["NOT", "NOT OFFENSIVE", "LABEL_0"],
        ),
        Label(
            name="OFFENSIVE",
            synonyms=["OFF", "LABEL_1"],
        ),
```

2022-09-07 12:36 UTC, saattrupdan commented
Looks good to me - just missing the unit test fix.

2022-09-13 08:31 UTC, AJDERS commented
Closing this as solving conflicts is slower than doing it from the start once more.

2022-09-13 08:31 UTC, closed without merging