Adding ASR
alexandrainst/AIAI-eval pull request #86
Opened 2022-10-26 09:25 UTC by AJDERS

Draft

2022-10-31 10:07 UTC, saattrupdan requested changes

2022-10-31 10:07 UTC, saattrupdan commented on src/aiai_eval/utils.py
> +    ]
This list will always have exactly 0 or 1 element, which seems a bit silly. Why not use the previous Boolean value?

2022-10-31 10:07 UTC, saattrupdan commented on src/aiai_eval/utils.py
> +            which are allowed for the supertask.
This is quite confusion. What's the difference between "valid" and "allowed"?

2022-10-31 10:07 UTC, saattrupdan commented on tests/conftest.py
> +        "automatic-speech-recognition": ["openai/whisper-small"],
Maybe use tiny, to make tests faster?

2022-10-31 10:07 UTC, saattrupdan commented on tests/test_utils.py
> +            "token-classification",
Shouldn't `allowed_architectures` be a sequence?

2022-10-31 10:07 UTC, saattrupdan commented on pyproject.toml
> +pypi-kenlm = "^0.1.20220713"
We should maybe consider making these dependencies optional.

2022-10-31 10:23 UTC, AJDERS commented on src/aiai_eval/automatic_speech_recognition.py
> +            ]
Not the only difference, one has `input_values[0]` the other has `input_features[0]`.

2022-10-31 10:25 UTC, AJDERS commented on src/aiai_eval/automatic_speech_recognition.py
> +        )
True!

2022-10-31 12:16 UTC, AJDERS commented on src/aiai_eval/task.py
> +                if self.task_config.name == "automatic-speech-recognition"
Yup! Ill open an issue.

2022-10-31 12:52 UTC, AJDERS commented on src/aiai_eval/task.py
> +                    elif not isinstance(model_predictions, torch.Tensor):
`model_predictions = model.generate` outputs `torch.Tensor`'s which would give an error with the previous code. Now if the output does not have `logits` or `start_logits`/`end_logits`, we check if it is even a tensor, and if not, well we throw an error.

Would a more descriptive comment help? Or are you thinking something else? :)

2022-10-31 13:10 UTC, AJDERS commented on src/aiai_eval/task.py
>                  all_predictions.extend(model_predictions)
Yup :)

2022-10-31 14:58 UTC, AJDERS commented on pyproject.toml
> +pypi-kenlm = "^0.1.20220713"
Yes that might be a good idea.

2023-01-05 10:32 UTC, saattrupdan requested changes

2023-01-05 10:32 UTC, saattrupdan commented on pyproject.toml
> +torchaudio = "^0.13.1"
The behaviour of "^" is a bit odd for some reason. For instance, "^1.2.3" means ">=1.2.3, <2.0.0", which is correct, but "^0.1.2" means ">=0.1.2, <0.2.0", so suddenly we're not supporting the next minor version. We can fix this by making these "zero-major versions" more explicit:

```suggestion
soundfile = ">=0.11.0,<1.0.0"
evaluate = ">=0.3.0,<1.0.0"
pyctcdecode = ">=0.4.0,<1.0.0"
pypi-kenlm = ">=0.1.20220713,<1.0.0"
librosa = ">=0.9.2,<1.0.0"
torch = "^1.13.1"
torchaudio = ">=0.13.1,<1.0.0"
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/config.py
> +        modality str:
```suggestion
        modality (str):
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/config.py
> +            The modality of the input data.
Maybe mention what the choices are?

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/config.py
> +            The architectures that can be used to solve the task. Defaults to None.
```suggestion
            The architectures that can be used to solve the task. If None then
            it defaults to the list containing only the name of the supertaks. Defaults 
            to None.
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/hf_hub_utils.py
> +    # try to load a processor from the model id, if it does not exist, then set
```suggestion
    # Try to load a processor from the model id, if it does not exist, then set
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/metric_configs.py
> +    postprocessing_fn=lambda raw_score: str(raw_score),
Why not truncate the number of decimals here, like the others?
```suggestion
    postprocessing_fn=lambda raw_score: f"{raw_score:.4f}",
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/named_entity_recognition.py
> +            leaves_are_floats = sample_preds[0][0].dtype.kind == "f"
A slight simplification. Mostly for style points, I don't mind if you leave it as is.

```suggestion
        leaves_are_floats = not elements_are_strings and sample_preds[0][0].dtype.kind == "f"
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/task.py
> +            # If the processor is not a tokenizer we assume its a processor
```suggestion
            # If the processor is not a tokenizer we assume it's a processor, and
```

2023-01-05 10:32 UTC, saattrupdan commented on tests/conftest.py
> +            "alexandrainst/da-electra-hatespeech-detection"
Changed the model name again, sorry. All models in our repo now follow the format "<language>-<task>-<size>".

```suggestion
            "alexandrainst/da-hatespeech-detection-small"
```

2023-01-05 10:32 UTC, saattrupdan commented on tests/conftest.py
> +        "alexandrainst/da-electra-hatespeech-detection": dict(
Same as above.

```suggestion
        "alexandrainst/da-hatespeech-detection-small": dict(
```

2023-01-05 10:32 UTC, saattrupdan commented on src/aiai_eval/config.py
> +            The modality of the input data.
Consider making the modalities into an enum, just like `Framework`, to make it clearer.

2023-01-05 12:56 UTC, saattrupdan requested changes
Looks great! Only a tiny change left in the dependencies.

2023-01-05 12:56 UTC, saattrupdan commented on pyproject.toml
>  sentencepiece = "^0.1.96"
```suggestion
sentencepiece = ">=0.1.96,<1.0.0"
```

2023-01-05 15:34 UTC, saattrupdan approved these changes
LGTM!

2023-01-05 15:55 UTC, merged